config/routes.rb
Rails.application.routes.draw do
  devise_for :users#, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root to: 'application#index'
  get "users/active", to:"users#active", as: :active_users
  get "versions/:item_type(/:item_id)", to:"versions#index", as: :versions
  get "user_versions/:whodunnit", to:"versions#user_versions", as: :user_versions
  post "users/active/change/:id", to:"users#toggle_active", as: :toggle_active
  post "users/switch", to:"users#switch_user", as: :switch_user
  post "users/admin/change/:id", to:"users#toggle_admin", as: :toggle_admin

  namespace :contur do
    resources :customers
    resources :servers
    resources :databases
  end

  devise_scope :user do
    get 'login', to: 'devise/sessions#new'
    get 'signup', to: 'devise/registrations#new'
  end

  resources :users
  get 'edit_profile', to: 'users#edit_profile', as: :edit_profile
  patch 'update_profile', to: 'users#update_profile', as: :update_profile
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :set_locale, :set_paper_trail_whodunnit

  def index
    @users = User.limit(10).order(created_at: :desc)
  end

  def require_admin!
    if !current_user.admin?
      redirect_back(fallback_location: root_path, flash: {error: I18n.t("flash.general.denied")})
    end
  end

  def set_locale
    if current_user
      I18n.locale = current_user.locale
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_error_key(key)
    case key
    when "error"
      "danger"
    when "notice"
      "success"
    else
      key
    end
  end

  def form_search_value(param_values, attribute)
    param_values[attribute] if param_values.present?
  end
end

app/views/application/partials/_admin_dashboard.html.haml
%h1.centered= I18n.t("views.application.index.welcome")
%hr
%br
.row.justify-content-center
  .col-sm-5
    .card_block
      %h1.header.centered
        = I18n.t("views.application.index.user_header")
      %ul.default_list
        .table_container
          %table.default.table_centered_elements
            %thead.thead-dark
              %tr
                %th= User.human_attribute_name(:name)
                %th= User.human_attribute_name(:email)
                %th= User.human_attribute_name(:account_active)
                %th= t "actions.actions"
            %tbody
              - @users = User.order(:id).reverse.first(5)
              - @users.each do |user|
                %tr
                  %td= user.name
                  %td
                    %span.fas.fa-envelope
                    = user.email
                  %td
                    = user.decorate.active_mark
                  %td
                    = link_to user_path(user) do
                      %i.fas.fa-search{"data-placement" => "bottom", "data-toggle" => "tooltip", title: "#{I18n.t("tooltips.show", model: User.model_name.human, count: 1)}"}
                    = link_to edit_user_path(user) do
                      %i.fas.fa-edit{"data-placement" => "bottom", "data-toggle" => "tooltip", title: "#{I18n.t("tooltips.edit", model: User.model_name.human, count: 1)}"}
                    = link_to user_path(user), method: :delete, data: {confirm: "#{I18n.t("flash.delete", model: User.model_name.human, count: 1)}"} do
                      %i.fas.fa-trash-alt{"data-placement" => "bottom", "data-toggle" => "tooltip", title: "#{I18n.t("tooltips.delete", model: User.model_name.human, count: 1)}"}
          %li.centered{"data-placement" => "bottom", "data-toggle" => "tooltip", title: "#{I18n.t("tooltips.show", model: User.model_name.human, count: 1)}"}
            = link_to users_path do
              %i.fas.fa-eye

  .col-sm-5
    .card_block
      %h1.header.centered
        = I18n.t("views.application.index.server_header")
      %ul.default_list
        .table_container
          %table.default.table_centered_elements
            %thead.thead-dark
              %tr
                %th= Contur::Server.human_attribute_name(:hostname)
                %th= Contur::Server.human_attribute_name(:admin_user)
                %th= Contur::Server.human_attribute_name(:os_version)
                %th= Contur::Server.human_attribute_name(:ruby_version)
                %th= Contur::Server.human_attribute_name(:access_type)
                %th= t "actions.actions"
            %tbody
              - @servers = Contur::Server.order(:id).reverse.first(5)
              - @servers.each do |server|
                %tr
                  %td= server.hostname
                  %td
                    %span.fas.fa-tools
                    = server.admin_user
                  %td
                    %span.fas.fa-cloud-download-alt
                    = server.os_version
                  %td
                    %span.fas.fa-cloud-download-alt
                    = server.ruby_version
                  %td
                    %span.fas.fa-ethernet
                    = server.access_type
                  %td
                    = link_to contur_server_path(server) do
                      %i.fas.fa-search{"data-placement" => "bottom", "data-toggle" => "tooltip", title: "#{I18n.t("tooltips.show", model: Contur::Server.model_name.human, count: 1)}"}
                    = link_to edit_contur_server_path(server) do
                      %i.fas.fa-edit{"data-placement" => "bottom", "data-toggle" => "tooltip", title: "#{I18n.t("tooltips.edit", model: Contur::Server.model_name.human, count: 1)}"}
                    = link_to contur_server_path(server), method: :delete, data: {confirm: I18n.t("flash.delete", model: Contur::Server.model_name.human, count: 1)} do
                      %i.fas.fa-trash-alt{"data-placement" => "bottom", "data-toggle" => "tooltip", title: "#{I18n.t("tooltips.delete", model: Contur::Server.model_name.human, count: 1)}"}
        %li.centered{"data-placement" => "bottom", "data-toggle" => "tooltip", title: "#{I18n.t("tooltips.show", model: Contur::Server.model_name.human, count: 1)}"}
          = link_to contur_servers_path do
            %i.fas.fa-eye

.row.justify-content-center
  .col-sm-5
    %canvas#barChart

app/views/application/partials/_not_admin_dashboard.html.haml
%h1.centered= t "views.application.index.welcome"