config/routes.rb
Rails.application.routes.draw do
  devise_for :users#, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root to: 'application#index'
  get "users/active", to:"users#active", as: :active_users
  get "versions/:item_type(/:item_id)", to:"versions#index", as: :versions
  get "user_versions/:whodunnit", to:"versions#user_versions", as: :user_versions
  post "users/active/change/:id", to:"users#toggle_active", as: :toggle_active
  post "users/switch", to:"users#switch_user", as: :switch_user
  post "users/admin/change/:id", to:"users#toggle_admin", as: :toggle_admin

  namespace :contur do
    resources :customers
    resources :servers
    resources :databases
  end

  devise_scope :user do
    get 'login', to: 'devise/sessions#new'
    get 'signup', to: 'devise/registrations#new'
  end

  resources :users
  get 'edit_profile', to: 'users#edit_profile', as: :edit_profile
  patch 'update_profile', to: 'users#update_profile', as: :update_profile
end

app/models/contur.rb
module Contur
  def self.table_name_prefix
    'contur_'
  end
end

app/models/contur/customer.rb
class Contur::Customer < ApplicationRecord
  has_many :server,
    class_name: "Contur::Server",
    foreign_key: :customer_id,
    dependent: :destroy

  has_many :databases, through: :server

  def self.search(query)
    scope = all
    if query[:id].present?
      scope = scope.id_search(query[:id])
    end

    if query[:name].present?
      scope = scope.url_search(query[:name])
    end

    if query[:email].present?
      scope = scope.vm_search(query[:email])
    end

    if query[:phone_number].present?
      scope = scope.git_search(query[:phone_number])
    end

    if query[:zip_code].present?
      scope = scope.server_search(query[:zip_code])
    end

    if query[:street].present?
      scope = scope.type_search(query[:street])
    end

    if query[:tanss_number].present?
      scope = scope.type_search(query[:tanss_number])
    end

    scope
  end

  def self.id_search(query)
    where("id = :id", id: query)
  end

  def self.name_search(query)
    where("name ILIKE :name", name: "%#{query}%")
  end

  def self.email_search(query)
    where("email ILIKE :email", email: "%#{query}%")
  end

  def self.phone_search(query)
    where("phone_number ILIKE :phone_number", phone_number: "%#{query}%")
  end

  def self.zip_search(query)
    where("zip_code = :zip_code", zip_code: "%#{query}%")
  end

  def self.street_search(query)
    where("street ILIKE :street", street: "%#{query}%")
  end

  def self.tanss_search(query)
    where("tanss_number ILIKE :tanss_number", tanss_number: "%#{query}%")
  end
end

app/models/contur/database.rb
class Contur::Database < ApplicationRecord
  CONTUR = "contur".freeze
  BABYLOTSE = "babylotse".freeze
  NACHSORGE = "nachsorge".freeze
  KITA = "kita".freeze

  ANPASSUNGEN = [
    CONTUR,
    BABYLOTSE,
    NACHSORGE,
    KITA
  ]

  belongs_to :server,
    class_name: "Contur::Server",
    foreign_key: :server_id

  validates :vm_username, :contur_type, :starts_at, presence: true

  validates :contur_type, inclusion: { in: ANPASSUNGEN }

  validates :github_branch, uniqueness: true, presence: true
  validates :url, uniqueness: true, presence: true

  def self.search(query)
    scope = all
    if query[:id].present?
      scope = scope.id_search(query[:id])
    end

    if query[:url].present?
      scope = scope.url_search(query[:url])
    end

    if query[:vm_username].present?
      scope = scope.vm_search(query[:vm_username])
    end

    if query[:github_branch].present?
      scope = scope.git_search(query[:github_branch])
    end

    if query[:server_id].present?
      scope = scope.server_search(query[:server_id])
    end

    if query[:contur_type].present?
      scope = scope.type_search(query[:contur_type])
    end

    scope
  end

  def self.id_search(query)
    where("id = :id", id: query)
  end

  def self.url_search(query)
    where("url ILIKE :url", url: "%#{query}%")
  end

  def self.vm_search(query)
    where("vm_username ILIKE :vm_username", vm_username: "%#{query}%")
  end

  def self.git_search(query)
    where("github_branch ILIKE :github_branch", github_branch: "%#{query}%")
  end

  def self.server_search(query)
    where("server_id = :server_id", server_id: query)
  end

  def self.type_search(query)
    where("contur_type ILIKE :contur_type", contur_type: "%#{query}%")
  end
end

app/models/contur/server.rb
class Contur::Server < ApplicationRecord
  EXTERN = "Extern".freeze
  RZ = "RZ".freeze
  VPN = "VPN".freeze

  ACCESS = [
    EXTERN,
    RZ,
    VPN
  ]

  OS_VERSION = [
    "12.04",
    "14.04",
    "16.04",
    "18.04",
    "20.04"
  ]

  validates :os_version, :hostname, :admin_user, :access_type, presence: true

  has_many :databases,
    class_name: "Contur::Database",
    foreign_key: :server_id,
    dependent: :destroy

  belongs_to :customer,
    optional: true,
    class_name: "Contur::Customer",
    foreign_key: :customer_id

  def self.search(query)
    scope = all
    if query[:id].present?
      scope = scope.id_search(query[:id])
    end

    if query[:os_version].present?
      scope = scope.os_search(query[:os_version])
    end

    if query[:ruby_version].present?
      scope = scope.ruby_search(query[:ruby_version])
    end

    if query[:nginx_version].present?
      scope = scope.nginx_search(query[:nginx_version])
    end

    if query[:postgres_version].present?
      scope = scope.postgres_search(query[:postgres_version])
    end

    if query[:hostname].present?
      scope = scope.hostname_search(query[:hostname])
    end

    if query[:admin_user].present?
      scope = scope.admin_search(query[:admin_user])
    end

    if query[:access_type].present?
      scope = scope.access_search(query[:access_type])
    end

    if query[:database_id].present?
      scope = scope.database_search(query[:database_id])
    end

    scope
  end

  def self.id_search(query)
    where("id = :id", id: query)
  end

  def self.os_search(query)
    where("os_version ILIKE :os_version", os_version: "%#{query}%")
  end

  def self.ruby_search(query)
    where("ruby_version ILIKE :ruby_version", ruby_version: "%#{query}%")
  end

  def self.nginx_search(query)
    where("nginx_version ILIKE :nginx_version", nginx_version: "%#{query}%")
  end

  def self.postgres_search(query)
    where("postgres_version ILIKE :postgres_version", postgres_version: "%#{query}%")
  end

  def self.hostname_search(query)
    where("hostname ILIKE :hostname", hostname: "%#{query}%")
  end

  def self.admin_search(query)
    where("admin_user ILIKE :admin_user", admin_user: "%#{query}%")
  end

  def self.access_search(query)
    where("access_type ILIKE :access_type", access_type: "%#{query}%")
  end

  def self.database_search(query)
    joins(:databases).where("contur_databases.id = ?", query)
  end
end

app/controllers/contur/customers_controller.rb
class Contur::CustomersController < ApplicationController

  def index
    if params[:query]
      @cs = Contur::Customer.search(params[:query]).page params[:page]
    else
      @cs = Contur::Customer.order(:id).page params[:page]
    end

    respond_to do |format|
      format.html
      format.csv {
        @csv = Contur::CustomerCsv.new(@cs.limit(nil).offset(nil))
        send_data @csv.to_csv
      }
    end
  end

  def show
    @cr = Contur::Customer.find(params[:id]).decorate
  end

  def new
    @cr = Contur::Customer.new
  end

  def create
    @cr = Contur::Customer.new(create_params)

    if @cr.save
      redirect_to contur_customers_path, flash: {success: I18n.t("flash.created", model: Contur::Customer.model_name.human, count: 1)}
    else
      flash[:danger] = I18n.t("flash.creation_error", model: Contur::Customer.model_name.human, count: 1)
      render "new"
    end
  end

  def edit
    @cr = Contur::Customer.find(params[:id])
  end

  def update
    @cr = Contur::Customer.find(params[:id])

    if @cr.update_attributes(update_params)
      redirect_to contur_customers_path, flash: {success: I18n.t("flash.update", model: Contur::Customer.model_name.human, count: 1)}
    else
      render "edit"
    end
  end

  def destroy
    @cr = Contur::Customer.find(params[:id])
    @cr.destroy

    redirect_to contur_customers_path, flash: {success: I18n.t("flash.deleted", model: Contur::Customer.model_name.human, count: 1)}
  end

  def to_csv

  end

  private

  def create_params
    params.require(:contur_customer).permit( :name,
                                             :email,
                                             :phone_number,
                                             :fax,
                                             :zip_code,
                                             :city,
                                             :street,
                                             :tanss_number,
                                             :website,
                                             :comment
                                           )
  end

  def update_params
    params.require(:contur_customer).permit( :name,
                                             :email,
                                             :phone_number,
                                             :fax,
                                             :zip_code,
                                             :city,
                                             :street,
                                             :tanss_number,
                                             :website,
                                             :comment
                                           )
  end
end

app/controllers/contur/databases_controller.rb
class Contur::DatabasesController < ApplicationController

  def index
    if params[:query]
      @dbs = Contur::Database.search(params[:query]).page params[:page]
    else
      @dbs = Contur::Database.order(:id).page params[:page]
    end

    respond_to do |format|
      format.html
      format.csv {
        @csv = Contur::DatabaseCsv.new(@dbs.limit(nil).offset(nil))
        send_data @csv.to_csv
      }
    end
  end

  def show
    @db = Contur::Database.find(params[:id]).decorate
  end

  def new
    @db = Contur::Database.new
  end

  def create
    @db = Contur::Database.new(create_params)

    if @db.save
      redirect_to contur_databases_path, flash: {success: I18n.t("flash.created", model: Contur::Database.model_name.human, count: 1)}
    else
      flash[:danger] = I18n.t("flash.creation_error", model: Contur::Database.model_name.human, count: 2)
      render "new"
    end
  end

  def edit
    @db = Contur::Database.find(params[:id])
  end

  def update
    @db = Contur::Database.find(params[:id])

    if @db.update_attributes(update_params)
      redirect_to contur_databases_path, flash: {success: I18n.t("flash.update", model: Contur::Database.model_name.human, count: 1)}
    else
      render "edit"
    end
  end

  def destroy
    @db = Contur::Database.find(params[:id])
    @db.destroy

    redirect_to contur_databases_path, flash: {success: I18n.t("flash.deleted", model: Contur::Database.model_name.human, count: 1)}
  end

  private

  def create_params
    params.require(:contur_database).permit( :url,
                                             :vm_username,
                                             :contur_type,
                                             :github_branch,
                                             :server_id,
                                             :starts_at,
                                             :ends_at,
                                             :comment
                                           )
  end

  def update_params
    params.require(:contur_database).permit( :url,
                                             :vm_username,
                                             :contur_type,
                                             :github_branch,
                                             :server_id,
                                             :starts_at,
                                             :ends_at,
                                             :comment
                                           )
  end
end

app/controllers/contur/servers_controller.rb
class Contur::ServersController < ApplicationController
  def index
    if params[:query]
      @servers = Contur::Server.search(params[:query]).page params[:page]
    else
      @servers = Contur::Server.order(:id).page params[:page]
    end

    respond_to do |format|
      format.html
      format.csv {
        @csv = Contur::ServerCsv.new(@servers.limit(nil).offset(nil))
        send_data @csv.to_csv
      }
    end
  end

  def show
    @server = Contur::Server.find(params[:id]).decorate
  end

  def new
    @server = Contur::Server.new
  end

  def create
    @server = Contur::Server.new(create_params)

    if @server.save
      redirect_to contur_servers_path, flash: {success: I18n.t("flash.created", model: Contur::Server.model_name.human, count: 1)}
    else
      flash[:danger] = I18n.t("flash.creation_error", model: Contur::Server.model_name.human, count: 1)
      render "new"
    end
  end

  def edit
    @server = Contur::Server.find(params[:id])
  end

  def update
    @server = Contur::Server.find(params[:id])

    if @server.update_attributes(update_params)
      redirect_to contur_servers_path, flash: {success: I18n.t("flash.update", model: Contur::Server.model_name.human, count: 1)}
    else
      @server.valid?
      puts @server.errors.inspect
      render "edit"
    end
  end

  def destroy
    @server = Contur::Server.find(params[:id])
    @server.destroy

    redirect_to contur_servers_path, flash: {success: I18n.t("flash.deleted", model: Contur::Server.model_name.human, count: 1)}
  end

  private

  def create_params
    params.require(:contur_server).permit( :os_version,
                                           :ruby_version,
                                           :nginx_version,
                                           :postgres_version,
                                           :hostname,
                                           :admin_user,
                                           :access_type,
                                           :ip_address,
                                           :ssh_password,
                                           :ssh_port,
                                           :customer_id,
                                           :comment,
                                           :rz_access
                                           )
  end

  def update_params
    params.require(:contur_server).permit( :os_version,
                                           :ruby_version,
                                           :nginx_version,
                                           :postgres_version,
                                           :hostname,
                                           :admin_user,
                                           :access_type,
                                           :ip_address,
                                           :ssh_password,
                                           :ssh_port,
                                           :customer_id,
                                           :comment,
                                           :rz_access
                                           )
  end
end

app/views/contur/servers/edit.html.haml
.container.col-sm-6.index
  %h1.centered= I18n.t("views.contur/servers.edit.edit")
  %hr
  = simple_form_for(@server) do |f|
    .row.justify-content-center
      .col-sm-6
        = f.input :os_version, placeholder: Contur::Server.human_attribute_name(:os_version)
        = f.input :ruby_version, placeholder: Contur::Server.human_attribute_name(:ruby_version)
      .col-sm-6
        = f.input :nginx_version, placeholder: Contur::Server.human_attribute_name(:nginx_version)
        = f.input :postgres_version, placeholder: Contur::Server.human_attribute_name(:postgres_version)
    .row.justify-content-center
      .col-sm-6
        = f.input :hostname, placeholder: Contur::Server.human_attribute_name(:hostname)
      .col-sm-6
        = f.input :admin_user, placeholder: Contur::Server.human_attribute_name(:admin_user)
    .row.justify-content-center
      .col-sm-6
        = f.input :access_type, placeholder: Contur::Server.human_attribute_name(:access_type), as: :select, collection: Contur::Server::ACCESS
      .col-sm-6
        = f.association :customer, as: :select, collection: Contur::Customer.order(:name)
    .row.justify-content-center
      .col-sm-12
        = f.input :comment, placeholder: Contur::Server.human_attribute_name(:comment)
    %h2.centered= I18n.t("views.contur/servers.ssh_access")
    %hr
    .row.justify-content-center
      .col-sm-4
        = f.input :ip_address, placeholder: Contur::Server.human_attribute_name(:ip_address)
      .col-sm-4
        = f.input :ssh_port, placeholder: Contur::Server.human_attribute_name(:ssh_port)
      .col-sm-4
        = f.input :ssh_password, placeholder: Contur::Server.human_attribute_name(:ssh_password)
    .row.justify-content-center
      .col-sm-12
        = f.input :rz_access, as: :boolean, hint: "Nur Zugriff über die IP des Rechenzentrums möglich"
    %hr
    .row.justify-content-center
      .col-sm-8
        = f.submit I18n.t("actions.update"), class: "form-control"
  .row.justify-content-center
    .col-sm-8
      = button_to I18n.t("views.contur/servers.edit.delete"), contur_server_path(@server), method: :delete, class: "form-control", id: "delete_server_button", data: {confirm: I18n.t("flash.delete", model: Contur::Server.model_name.human, count: 1)}
      = button_to I18n.t("actions.back"), :back, method: :get, class: "form-control", id: "back_to_root_button"
  %br

app/views/contur/servers/index.html.haml
.container.index
  %h1.header= I18n.t("views.contur/servers.index.header")
  %p{"aria-expanded" => "false", "data-toggle" => "collapse", :href => "#filters", id: "filters-data-toggle"}
    %i.fas.fa-filter{:style => "cursor: pointer"}
      = I18n.t("actions.filter")
  -if params[:query]
    = render partial: "contur/servers/partials/showed_filter"
  -else
    = render partial: "contur/servers/partials/hidden_filter"
  .table_container
    %table.default.table_centered_elements
      %thead.thead-dark
        %tr
          %th= Contur::Server.human_attribute_name(:id)
          %th= Contur::Server.human_attribute_name(:hostname)
          %th= Contur::Server.human_attribute_name(:admin_user)
          %th= Contur::Server.human_attribute_name(:os_version)
          %th= Contur::Server.human_attribute_name(:ruby_version)
          %th= Contur::Server.human_attribute_name(:access_type)
          %th= t "actions.actions"
      %tbody
        - @servers.each do |server|
          %tr
            %td= server.id
            %td= server.hostname
            %td
              %span.fas.fa-tools
              = server.admin_user
            %td
              %span.fas.fa-cloud-download-alt
              = server.os_version
            %td
              %span.fas.fa-cloud-download-alt
              = server.ruby_version
            %td
              %span.fas.fa-ethernet
              = server.access_type
            %td
              = link_to contur_server_path(server) do
                %i.fas.fa-search{"data-placement" => "bottom", "data-toggle" => "tooltip", title: "#{I18n.t("tooltips.show", model: Contur::Server.model_name.human, count: 1)}"}
              = link_to edit_contur_server_path(server) do
                %i.fas.fa-edit{"data-placement" => "bottom", "data-toggle" => "tooltip", title: "#{I18n.t("tooltips.edit", model: Contur::Server.model_name.human, count: 1)}"}
              = link_to contur_server_path(server), method: :delete, data: {confirm: I18n.t("flash.delete", model: Contur::Server.model_name.human, count: 1)} do
                %i.fas.fa-trash-alt{"data-placement" => "bottom", "data-toggle" => "tooltip", title: "#{I18n.t("tooltips.delete", model: Contur::Server.model_name.human, count: 1)}"}
  .row.justify-content-center.pagination_buttons
    = paginate @servers
  %br
  .row.justify-content-center
    = link_to contur_servers_path(format: :csv) do
      %i.fas.fa-file-download
      = "Download .csv"
  %br

app/views/contur/servers/new.html.haml
.container.col-sm-6.index
  %h1.header= t "views.contur/servers.new.header"
  %hr
  = simple_form_for(@server, url: contur_servers_path) do |f|
    .row.justify-content-center
      .col-sm-6
        = f.input :os_version, placeholder: Contur::Server.human_attribute_name(:os_version), as: :select, collection: Contur::Server::OS_VERSION
        = f.input :ruby_version, placeholder: Contur::Server.human_attribute_name(:ruby_version)
      .col-sm-6
        = f.input :nginx_version, placeholder: Contur::Server.human_attribute_name(:nginx_version)
        = f.input :postgres_version, placeholder: Contur::Server.human_attribute_name(:postgres_version)
    .row.justify-content-center
      .col-sm-6
        = f.input :hostname, placeholder: Contur::Server.human_attribute_name(:hostname)
      .col-sm-6
        = f.input :admin_user, placeholder: Contur::Server.human_attribute_name(:admin_user)
    .row.justify-content-center
      .col-sm-6
        = f.input :access_type, placeholder: Contur::Server.human_attribute_name(:access_type), as: :select, collection: Contur::Server::ACCESS
      .col-sm-6
        = f.association :customer, as: :select, collection: Contur::Customer.order(:name)
    .row.justify-content-center
      .col-sm-12
        = f.input :comment, placeholder: Contur::Server.human_attribute_name(:comment)
    %h2.centered= I18n.t("views.contur/servers.ssh_access")
    %hr
    .row.justify-content-center
      .col-sm-4
        = f.input :ip_address, placeholder: Contur::Server.human_attribute_name(:ip_address)
      .col-sm-4
        = f.input :ssh_port, placeholder: Contur::Server.human_attribute_name(:ssh_port)
      .col-sm-4
        = f.input :ssh_password, placeholder: Contur::Server.human_attribute_name(:ssh_password)
    .row.justify-content-center
      .col-sm-12
        = f.input :rz_access, as: :boolean, hint: "Nur Zugriff über die IP des Rechenzentrums möglich"
    %hr
    .row.justify-content-center
      .col-sm-8
        = f.submit I18n.t("actions.create"), class: "form-control"
        = link_to I18n.t("actions.back"), :back, method: :get, class: "form-control centered", id: "back_to_root_button"
  %br

app/views/contur/servers/show.html.haml
.container.index.max
  .card_block
    %h1.header= "#{I18n.t("views.contur/servers.show.header", model: @server.hostname)}"
    %ul.default_list
      =@server.card_block_attr(:os_version)
      =@server.card_block_attr(:ruby_version)
      =@server.card_block_attr(:nginx_version)
      =@server.card_block_attr(:postgres_version)
      =@server.card_block_attr(:hostname)
      =@server.card_block_attr(:admin_user)
      =@server.card_block_attr(:access_type)
      =@server.card_block_attr(:comment)
      -if @server.customer.present?
        %li
          %dl.row
            %dt.col-sm-3= Contur::Server.human_attribute_name(:customer)
            %dd.col-sm-9
              -cs = Contur::Customer.find(@server.customer_id)
              =link_to cs.name, contur_customer_path(cs)
      -else
        %li
          %dl.row
            %dt.col-sm-3= Contur::Server.human_attribute_name(:customer)
            %dd.col-sm-9= "N/A"
      -if @server.databases.any?
        %li
          %dl.row
            %dt.col-sm-3= I18n.t("views.contur/servers.show.dbs")
            %dd.col-sm-9
              -@server.databases.each do |db|
                -database = Contur::Database.find(db.id)
                =link_to db.vm_username, contur_database_path(database)
      -else
        %li
          %dl.row
            %dt.col-sm-3= I18n.t("views.contur/servers.show.dbs")
            %dd.col-sm-9= "N/A"
  -if @server.ip_address.present?||@server.ssh_password.present?||@server.rz_access
    .card_block
      %h1.header= "#{I18n.t("views.contur/servers.ssh_access", model: @server.hostname)}"
      %ul.default_list
        %li
          %dl.row
            %dt.col-sm-3= Contur::Server.human_attribute_name(:ip_address)
            %dd.col-sm-9= @server.ip_address
            %dt.col-sm-3= Contur::Server.human_attribute_name(:ssh_password)
            %dd.col-sm-9= @server.ssh_password
            %dt.col-sm-3= Contur::Server.human_attribute_name(:ssh_port)
            %dd.col-sm-9= @server.ssh_port
            %dt.col-sm-3= Contur::Server.human_attribute_name(:rz_access)
            %dd.col-sm-9= @server.rz_bool
            -if @server.rz_access == true
              %dt.col-sm-3= Contur::Server.human_attribute_name(:ssh_command)
              %dd.col-sm-9= "ssh #{@server.admin_user}@#{@server.ip_address} -p #{@server.ssh_port} -L 3010:localhost:3000"
  %br
  .row.justify-content-center
    .col-sm-4
      = button_to I18n.t("actions.back"), :back, method: :get, class: "form-control", id: "back_to_root_button"
    .col-sm-4
      = button_to t("actions.edit"), edit_contur_server_path(@server), method: :get, class: "form-control", id: "edit_server_button"
  %br