config/routes.rb
Rails.application.routes.draw do
  devise_for :users#, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root to: 'application#index'
  get "users/active", to:"users#active", as: :active_users
  get "versions/:item_type(/:item_id)", to:"versions#index", as: :versions
  get "user_versions/:whodunnit", to:"versions#user_versions", as: :user_versions
  post "users/active/change/:id", to:"users#toggle_active", as: :toggle_active
  post "users/switch", to:"users#switch_user", as: :switch_user
  post "users/admin/change/:id", to:"users#toggle_admin", as: :toggle_admin

  namespace :contur do
    resources :customers
    resources :servers
    resources :databases
  end

  devise_scope :user do
    get 'login', to: 'devise/sessions#new'
    get 'signup', to: 'devise/registrations#new'
  end

  resources :users
  get 'edit_profile', to: 'users#edit_profile', as: :edit_profile
  patch 'update_profile', to: 'users#update_profile', as: :update_profile
end

app/models/user.rb
class User < ApplicationRecord
  has_paper_trail
  validates :email, format: { with: URI::MailTo::EMAIL_REGEXP }
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable

  def update_user_data(params)
    if params[:password].blank?
      params.delete("password")
      params.delete("password_confirmation")
    end

    self.update_attributes(params)
  end

   def active_for_authentication?
      # Uncomment the below debug statement to view the properties of the returned self model values.
      # logger.debug self.to_yaml

      super && account_active?
    end

  def inactive_message
    account_active? ? super : :inactive
  end

  def self.search(query)
    scope = all
    if query[:id].present?
      scope = scope.id_search(query[:id])
    end

    if query[:name].present?
      scope = scope.name_search(query[:name])
    end

    if query[:email].present?
      scope = scope.email_search(query[:email])
    end

    if query[:account_active].present?
      scope = scope.active_search(query[:account_active])
    end

    scope
  end

  def self.id_search(query)
    where("id = :id", id: query)
  end

  def self.name_search(query)
    where("name ILIKE :name", name: "%#{query}%")
  end

  def self.email_search(query)
    where("email ILIKE :email", email: "%#{query}%")
  end

  def self.active_search(query)
    where("account_active = :account_active", account_active: query)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_admin!, only: [:index, :new, :create, :edit, :update, :destroy]

  def index
    if params[:query]
      @users = User.search(params[:query]).page params[:page]
    else
      @users = User.order(:id).page(params[:page])
    end
  end

  def active
    @users = User.order(:id)
    @active = []
    @inactive = []
    @users.each do |user|
      if user.account_active?
        @active << user
      else
        @inactive << user
      end
    end
  end

  def set_account_active(user)
    if user
      u= User.get(user)
      u.account_active = false
    end
  end

  def remove_account_active(user)
    if user
      u= User.get(user)
      u.account_active = false
    end
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(create_params)

    if @user.save
      redirect_to users_path, flash: {success: I18n.t("flash.created", model: User.model_name.human, count: 1)}
    else
      flash[:danger] = I18n.t("flash.creation_error", model: User.model_name.human, count: 1)
      render "new"
    end
  end

  def switch_user
    sign_out current_user
    @user = User.find(params[:new_session][:id])
    sign_in @user
    redirect_to root_path
  end

  def show
    @user = User.find(params[:id])
  end

  def edit_profile
    @user = current_user
  end

  def update_profile
    @user = current_user

    if @user.update_with_password(update_profile_params)
      set_locale
      redirect_to root_path, flash: {success: I18n.t("flash.update", model: User.model_name.human, count: 1)}
    else
      render "edit_profile"
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])

    if @user.update_user_data(account_update_params)
      set_locale
      redirect_to users_path, flash: {success: I18n.t("flash.update", model: User.model_name.human, count: 1)}
    else
      render "edit"
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy

    redirect_to users_path, flash: {success: I18n.t("flash.deleted", model: User.model_name.human, count: 1)}
  end

  def toggle_active
    @user = User.find(params[:id]).decorate
    if @user == current_user
      redirect_back(fallback_location: root_path, flash: {danger: I18n.t("flash.de/activation_error")})
    else
      @user.account_active = !@user.account_active
      @user.save(validate: false)

      redirect_back(fallback_location: root_path, flash: {success: @user.toggle_active_message})
    end
  end

  def toggle_admin
    @user = User.find(params[:id]).decorate

    @user.admin = !@user.admin
    @user.save(validate: false)

    redirect_back(fallback_location: root_path, flash: {success: @user.toggle_admin_message})
  end

  private

  def create_params
    params.require(:user).permit( :name,
                                  :email,
                                  :password,
                                  :password_confirmation,
                                  :account_active,
                                  :admin
                                )
  end

  def account_update_params
    params.require(:user).permit( :name,
                                  :email,
                                  :password,
                                  :password_confirmation,
                                  :account_active,
                                  :admin
                                )
  end

  def update_profile_params
    params.require(:user).permit( :name,
                                  :email,
                                  :password,
                                  :password_confirmation,
                                  :current_password,
                                  :locale
                                )
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_user_detail.html.haml
%li
  %dl.row
    %dt.col-sm-4= User.human_attribute_name(:id)
    %dd.col-sm-8#test
      = user.id
      = link_to toggle_active_path(user), method: :post do
        =user.decorate.toggle_switch
  %dl.row
    %dt.col-sm-4= User.human_attribute_name(:name)
    %dd.col-sm-8= user.name
  %dl.row
    %dt.col-sm-4= I18n.t("actions.show")
    %dd.col-sm-8
      = link_to user_path(user) do
        %i.fas.fa-search{"data-placement" => "bottom", "data-toggle" => "tooltip", title: "#{I18n.t("tooltips.show", model: User.model_name.human, count: 1)}"}
  %dl.row
    %dt.col-sm-4= I18n.t("views.users.active.status")
    %dd.col-sm-8
      = user.decorate.active_badge

app/views/users/active.html.haml
.container-fluid
  .row.justify-content-center
    .col-sm-5
      .card_block
        %h1.header= I18n.t("views.users.active.active")
        %ul.default_list
          -@active.each do |user|
            = render partial: "users/partials/user_detail", locals: {user: user}

    .col-sm-5
      .card_block
        %h1.header= I18n.t("views.users.active.inactive")
        %ul.default_list
          -@inactive.each do |user|
            = render partial: "users/partials/user_detail", locals: {user: user}

app/views/users/edit.html.haml
.container.col-sm-4.index
  %h1.header= I18n.t("views.users.edit.header")
  = simple_form_for(@user) do |f|
    = f.input :email, autocomplete: "email", placeholder: User.human_attribute_name(:name)
    = f.input :password, placeholder: User.human_attribute_name(:password)
    = f.input :password_confirmation, placeholder: User.human_attribute_name(:password_confirmation)
    .row
      .col.items_centered
        = f.input :admin, as: :boolean
      .col.items_centered
        = f.input :account_active, as: :boolean
    = f.submit I18n.t("actions.update"), class: "form-control"
  %h2.footer= I18n.t("views.users.edit.footer")
  = button_to I18n.t("actions.delete"), user_path(@user), method: :delete, class: "form-control", id: "delete_user_button", data: {confirm: I18n.t("flash.delete", model: User.model_name.human, count: 1)}
  = button_to I18n.t("actions.back"), :back, method: :get, class: "form-control", id: "back_to_root_button"
  %br

app/views/users/edit_profile.html.haml
.container.col-sm-4.index
  %h1.header= I18n.t("views.users.edit.header")
  = simple_form_for(@user, url: update_profile_path, method: :patch) do |f|
    = f.input :email, autocomplete: "email", placeholder: User.human_attribute_name(:name)
    = f.input :password, placeholder: User.human_attribute_name(:password)
    = f.input :password_confirmation, placeholder: User.human_attribute_name(:password_confirmation)
    = f.input :current_password, placeholder: User.human_attribute_name(:current_password)
    = f.input :locale, collection: [[I18n.t("general.de"), :de], [I18n.t("general.en"), :en]]
    = f.submit I18n.t("actions.update"), class: "form-control"
  = button_to I18n.t("actions.back"), :back, method: :get, class: "form-control", id: "back_to_root_button"
  %br

app/views/users/index.html.haml
.container.index
  %h1.header= I18n.t("views.users.index.header")
  %p{"aria-expanded" => "false", "data-toggle" => "collapse", :href => "#filters", id: "filters-data-toggle"}
    %i.fas.fa-filter{:style => "cursor: pointer"}
      = I18n.t("actions.filter")
  -if params[:query]
    = render partial: "users/partials/showed_filter"
  -else
    = render partial: "users/partials/hidden_filter"
  .table_container
    %table.default.table_centered_elements
      %thead.thead-dark
        %tr
          %th= User.human_attribute_name(:id)
          %th= User.human_attribute_name(:name)
          %th= User.human_attribute_name(:email)
          %th= User.human_attribute_name(:account_active)
          %th= t "actions.actions"
      %tbody
        - @users.each do |user|
          %tr
            %td= user.id
            %td= user.name
            %td
              %span.fas.fa-envelope
              = user.email
            %td
              = user.decorate.active_mark
            %td
              = link_to user_path(user) do
                %i.fas.fa-search{"data-placement" => "bottom", "data-toggle" => "tooltip", title: "#{I18n.t("tooltips.show", model: User.model_name.human, count: 1)}"}
              = link_to edit_user_path(user) do
                %i.fas.fa-edit{"data-placement" => "bottom", "data-toggle" => "tooltip", title: "#{I18n.t("tooltips.edit", model: User.model_name.human, count: 1)}"}
              = link_to user_path(user), method: :delete, data: {confirm: "#{I18n.t("flash.delete", model: User.model_name.human, count: 1)}"} do
                %i.fas.fa-trash-alt{"data-placement" => "bottom", "data-toggle" => "tooltip", title: "#{I18n.t("tooltips.delete", model: User.model_name.human, count: 1)}"}
  .row.justify-content-center.pagination_buttons
    = paginate @users

app/views/users/new.html.haml
.container.col-sm-4.index
  %h1.header= t "views.users.new.header"
  = simple_form_for(@user, url: users_path) do |f|
    = f.input :name, placeholder: User.human_attribute_name(:name)
    = f.input :email, placeholder: User.human_attribute_name(:email)
    = f.input :password, placeholder: User.human_attribute_name(:password)
    = f.input :password_confirmation, placeholder: User.human_attribute_name(:password_confirmation)
    .row
      .col.items_centered
        = f.input :admin, as: :boolean
      .col.items_centered
        = f.input :account_active, as: :boolean
    = f.submit I18n.t("actions.create"), class: "form-control"
  = button_to I18n.t("actions.back"), :back, method: :get, class: "form-control", id: "back_to_root_button"
  %br

app/views/users/show.html.haml
.container.index.max
  .card_block
    -if current_user.admin?
      -if current_user == @user
        = render partial: "users/partials/show_as_admin_current", locals: {user: @user}
      -else
        = render partial: "users/partials/show_as_admin", locals: {user: @user}
    -else
      = render partial: "users/partials/show_as_default", locals: {user: @user}
  %br
  .row.justify-content-center
    .col-sm-4
      = button_to I18n.t("actions.back"), :back, method: :get, class: "form-control", id: "back_to_root_button"
    .col-sm-4
      -if current_user.admin?
        -if current_user == @user
          = button_to t("actions.edit"), edit_profile_path, method: :get, class: "form-control", id: "edit_profile_button"
        -else
          = button_to t("actions.edit"), edit_user_path(@user), method: :get, class: "form-control", id: "edit_user_button"
      -else
        = button_to t("actions.edit"), edit_profile_path, method: :get, class: "form-control", id: "edit_profile_button"