config/routes.rb
Rails.application.routes.draw do
  devise_for :users#, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root to: 'application#index'
  get "users/active", to:"users#active", as: :active_users
  get "versions/:item_type(/:item_id)", to:"versions#index", as: :versions
  get "user_versions/:whodunnit", to:"versions#user_versions", as: :user_versions
  post "users/active/change/:id", to:"users#toggle_active", as: :toggle_active
  post "users/switch", to:"users#switch_user", as: :switch_user
  post "users/admin/change/:id", to:"users#toggle_admin", as: :toggle_admin

  namespace :contur do
    resources :customers
    resources :servers
    resources :databases
  end

  devise_scope :user do
    get 'login', to: 'devise/sessions#new'
    get 'signup', to: 'devise/registrations#new'
  end

  resources :users
  get 'edit_profile', to: 'users#edit_profile', as: :edit_profile
  patch 'update_profile', to: 'users#update_profile', as: :update_profile
end

app/views/layouts/sidebar/_admin.html.haml
%nav#sidebar
  .row
    .sidebar-header
      %h3= I18n.t("general.title")
    #dismiss
      %i.fas.fa-arrow-left
  %ul.list-unstyled.components
    %li
      = link_to root_path do
        = I18n.t("sidebar.home")
        %i.fas.fa-home
    %li
      %a{"aria-expanded" => "false", "data-toggle" => "collapse", :href => "#manageSubmenu", id: "lists-data-toggle"}
        = I18n.t("sidebar.manage.manage")
        %span.fas.fa-angle-down
      %ul#manageSubmenu.collapse.list-unstyled
        %li
          = link_to active_users_path do
            = I18n.t("sidebar.manage.active_users")
            %i.fas.fa-users
        %li
          = link_to new_user_path do
            = I18n.t("sidebar.manage.users_new")
            %i.fas.fa-user-shield
            %i.fas.fa-plus
        %li
          = link_to new_contur_customer_path do
            = I18n.t("sidebar.manage.customers_new")
            %i.fas.fa-user
            %i.fas.fa-plus
        %li
          = link_to new_contur_server_path do
            = I18n.t("sidebar.manage.servers_new")
            %i.fas.fa-server
            %i.fas.fa-plus
        %li
          = link_to new_contur_database_path(User) do
            = I18n.t("sidebar.manage.databases_new")
            %i.fas.fa-database
            %i.fas.fa-plus
    %li
      %a{"aria-expanded" => "false", "data-toggle" => "collapse", :href => "#listsSubmenu", id: "lists-data-toggle"}
        = I18n.t("sidebar.lists.lists")
        %span.fas.fa-angle-down
      %ul#listsSubmenu.collapse.list-unstyled
        %li
          = link_to users_path do
            = I18n.t("sidebar.lists.users")
            %i.fas.fa-user-shield
        %li
          = link_to contur_customers_path do
            = I18n.t("sidebar.lists.customers")
            %i.fas.fa-user
        %li
          = link_to contur_servers_path do
            = I18n.t("sidebar.lists.servers")
            %i.fas.fa-server
        %li
          = link_to contur_databases_path do
            = I18n.t("sidebar.lists.databases")
            %i.fas.fa-database
        %li
          = link_to versions_path(User) do
            = I18n.t("sidebar.lists.versions")
            %i.fas.fa-code-branch
    %li
      %a{"aria-expanded" => "false", "data-toggle" => "collapse", :href => "#accSubmenu", id: "acc-data-toggle"}
        = I18n.t("sidebar.account.actions")
        %span.fas.fa-angle-down
      %ul#accSubmenu.collapse.list-unstyled
        %li
          = link_to user_path(current_user) do
            = I18n.t("sidebar.account.info")
            %i.fas.fa-info
        %li
          = link_to edit_profile_path do
            = I18n.t("sidebar.account.edit")
            %i.fas.fa-edit
        %li
          = link_to admin_root_path do
            = I18n.t("sidebar.account.admin")
            %i.fas.fa-toolbox
    %li
      = link_to '#', data: {toggle: "modal", target: "#switchModal"} do
        = I18n.t("sidebar.login_as")
        %i.fas.fa-sign-in-alt

    %li
      = link_to destroy_user_session_path, method: :delete, data: {confirm: I18n.t("flash.general.logout")} do
        = I18n.t("sidebar.logout")
        %i.fas.fa-sign-out-alt

= render partial: "layouts/partials/modal"

app/views/layouts/sidebar/_not_admin.html.haml
%nav#sidebar
  #dismiss
    %i.fas.fa-arrow-left
  .sidebar-header
    %h3= I18n.t("general.title")
  %ul.list-unstyled.components
    %li
      = link_to user_path(current_user) do
        = I18n.t("sidebar.account.info")
        %i.fas.fa-info
    %li
      = link_to edit_profile_path do
        = I18n.t("sidebar.account.edit")
        %i.fas.fa-edit
    %li
      = link_to destroy_user_session_path, method: :delete, data: {confirm: I18n.t("flash.general.logout")} do
        = I18n.t("sidebar.logout")
        %i.fas.fa-sign-out-alt